/*
 * JS for otp generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '778c290a-d751-4f93-a082-8cea3f42d78e';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "otp",
    "location": "otp.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

function otp_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'otp_mobilelabel_2'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'otp';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var otp_onLoad = function() {
        otp_elementsExtraJS();
        otp_deviceEvents();
        otp_windowEvents();
        otp_elementsEvents();
    };
    // screen window events
    function otp_windowEvents() {
        $('#otp').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function otp_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function otp_elementsExtraJS() {
        // screen (otp) extra code
    };
    // screen elements handler
    function otp_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#otp").on("pagebeforeshow", "#otp", function(event, ui) {
        Apperyio.CurrentScreen = "otp";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    otp_onLoad();
};
$(document).off("pagecreate", "#otp").on("pagecreate", "#otp", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    otp_js();
});