/*
 * JS for startScreen generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '778c290a-d751-4f93-a082-8cea3f42d78e';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "otp",
    "location": "otp.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

function startScreen_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'startScreen_mobilelabel_2',
        'mobilegrid_3': 'startScreen_mobilegrid_3',
        'mobilegridcell_4': 'startScreen_mobilegridcell_4',
        'mobileselectmenu_9': 'startScreen_mobileselectmenu_9',
        'mobileselectmenu_9-0': 'startScreen_mobileselectmenu_9-0',
        'mobilegridcell_8': 'startScreen_mobilegridcell_8',
        'mobiletextinput_11': 'startScreen_mobiletextinput_11',
        'mobilegrid_12': 'startScreen_mobilegrid_12',
        'mobilegridcell_13': 'startScreen_mobilegridcell_13',
        'mobilebutton_17': 'startScreen_mobilebutton_17'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var startScreen_onLoad = function() {
        startScreen_elementsExtraJS();
        startScreen_deviceEvents();
        startScreen_windowEvents();
        startScreen_elementsEvents();
    };
    // screen window events
    function startScreen_windowEvents() {
        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code
        /* mobileselectmenu_9 */
        $("#startScreen_mobileselectmenu_9").parent().find("a.ui-btn").attr("tabindex", "1");
    };
    // screen elements handler
    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    startScreen_onLoad();
};
$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});